#!/usr/bin/env python3
"""Builds the ambience SAMPLES in assets/sound/ambience/ from the sources declared below.

Like tools/make_icons.py, the files are generated, not hand-edited: every sample is a CC0 recording
from Freesound, fetched, cut, looped, normalised and written as 16-bit FLAC (gapless: a loop point
survives, unlike MP3's encoder padding). Re-run after editing SOURCES; the recordings are cached.

    tools/harness/.venv/Scripts/python tools/make_ambience.py [name ...] [--audition]

Needs numpy + soundfile (tools/harness/requirements.txt). --audition also writes 16-bit WAVs of the
results into the cache and prints the imgtools command that draws their spectrograms.

What happens to a source:
  (both)  `highpass` Hz first, if set: wind rumble and handling noise under a bird or insect bed
          cost the music its bass and carry nothing of the place.
  loop    [start, end) seconds of the recording, the last `xfade` seconds folded over the start with
          an equal-power crossfade (so the end runs straight back into the beginning), loudness-
          normalised to `lufs` (ungated BS.1770), resampled to 48 kHz if needed.
  events  the recording is split into its individual calls (envelope above `thresh` dB below the
          loudest peak, at least `min_s` long, padded and faded), the `count` loudest kept, each
          peak-normalised to `peak` dBFS: <name>_1.flac ... for an "events" layer.

Downloads use Freesound's public HQ previews (128 kbps MP3). They are the same recordings under the
same licence; for lossless originals, download them while logged in and put them in the cache as
<id>.wav — a cached WAV is preferred over the preview.

Every source's licence is re-checked on its Freesound page (CC0 only) and credited in
assets/sound/ambience/CREDITS.txt, which this script writes.
"""
import argparse
import json
import math
import os
import re
import sys
import urllib.request

try:
    import numpy as np
    import soundfile as sf
except ImportError:
    sys.exit("make_ambience needs numpy + soundfile: tools/harness/.venv/Scripts/python -m pip install -r tools/harness/requirements.txt")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "assets", "sound", "ambience")
CACHE = os.path.join(REPO, "build", "ambience_cache")
# Files in OUT this script does not make (it never deletes them; they're credited here so a re-run
# keeps the note).
ORIGINAL_NOTE = ("Original to this project (made in FL Studio for Sat Light Sim, not generated by this script):\n"
                 "vlf_earth: VLF whistlers and chorus for medium Earth orbit.\n"
                 "firmament: a high-orbit pad.\n")
SR = 48000          # working rate
LOOP_SR = 32000     # loops are written at this rate: nothing a bed needs lives above 16 kHz, and the
                    # files are a third smaller (miniaudio resamples to the device rate at load)

# id: Freesound sound id; page: its URL path. Kinds: loop / events (see the module docstring).
SOURCES = [
    {"name": "crickets_field", "highpass": 300, "kind": "loop", "id": 175020, "page": "/people/sengjinn/sounds/175020/",
     "what": "field crickets around midnight", "start": 2, "end": 38, "xfade": 3, "lufs": -24},
    {"name": "tropical_night", "highpass": 120, "kind": "loop", "id": 370864, "page": "/people/Mrthenoronha/sounds/370864/",
     "what": "frogs and insects, thick vegetation, Brazil, night", "start": 2, "end": 38, "xfade": 3, "lufs": -24},
    {"name": "birds_forest", "highpass": 150, "kind": "loop", "id": 488328, "page": "/people/priesjensen/sounds/488328/",
     "what": "morning in a Swedish forest, songbirds", "start": 2, "end": 38, "xfade": 3, "lufs": -24},
    {"name": "birds_dawn", "highpass": 150, "kind": "loop", "id": 578523, "page": "/people/SamsterBirdies/sounds/578523/",
     "what": "dawn chorus, Washington", "start": 2, "end": 38, "xfade": 3, "lufs": -24},
    {"name": "jungle_day", "highpass": 150, "kind": "loop", "id": 583930, "page": "/people/rucisko/sounds/583930/",
     "what": "jungle around a Mayan pyramid, day", "start": 2, "end": 38, "xfade": 3, "lufs": -24},
    {"name": "city_day", "highpass": 60, "kind": "loop", "id": 129679, "page": "/people/jmbphilmes/sounds/129679/",
     "what": "city traffic heard from a first-floor window", "start": 2, "end": 38, "xfade": 3, "lufs": -24},
    {"name": "city_night", "highpass": 70, "kind": "loop", "id": 330427, "page": "/people/janbezouska/sounds/330427/",
     "what": "downtown Los Angeles late at night, semi-distant traffic from the 4th floor", "start": 2, "end": 44,
     "xfade": 3, "lufs": -24},
    {"name": "beach_waves", "highpass": 40, "kind": "loop", "id": 531015, "page": "/people/Noted451/sounds/531015/",
     "what": "ocean waves on a beach", "start": 2, "end": 44, "xfade": 4, "lufs": -24},
    {"name": "gull", "highpass": 300, "kind": "events", "id": 462462, "page": "/people/Soojay/sounds/462462/",
     "what": "a clean wildtrack of seagulls", "count": 6, "thresh": 20, "min_s": 0.3, "peak": -6},
]


def fetch(url, path=None):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 (SatLightSim make_ambience)"})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    if path:
        with open(path, "wb") as f:
            f.write(data)
    return data


def source_audio(src):
    """Cached original WAV if present, else the HQ preview (downloaded once). Also returns the author."""
    os.makedirs(CACHE, exist_ok=True)
    meta_path = os.path.join(CACHE, f"{src['id']}.json")
    if os.path.exists(meta_path):
        meta = json.load(open(meta_path))
    else:
        html = fetch("https://freesound.org" + src["page"]).decode("utf-8", "replace")
        lic = "CC0" if "publicdomain/zero" in html else None
        prev = re.search(r"https://cdn\.freesound\.org/previews/[^\"']+-hq\.mp3", html)
        title = re.search(r'og:audio:title" content="([^"]*)"', html)
        artist = re.search(r'og:audio:artist" content="([^"]*)"', html)
        meta = {"license": lic, "preview": prev.group(0) if prev else None,
                "title": title.group(1) if title else "", "author": artist.group(1) if artist else ""}
        json.dump(meta, open(meta_path, "w"), indent=1)
    if meta["license"] != "CC0":
        sys.exit(f"{src['name']}: freesound {src['id']} is not CC0 ({meta['license']}) - refusing to ship it")
    wav = os.path.join(CACHE, f"{src['id']}.wav")
    mp3 = os.path.join(CACHE, f"{src['id']}.mp3")
    path = wav if os.path.exists(wav) else mp3
    if path == mp3 and not os.path.exists(mp3):
        if not meta["preview"]:
            sys.exit(f"{src['name']}: no preview URL on {src['page']}")
        fetch(meta["preview"], mp3)
    x, sr = sf.read(path, dtype="float64", always_2d=True)
    if x.shape[1] == 1:
        x = np.repeat(x, 2, axis=1)
    return x[:, :2], sr, meta


def resample(x, sr):
    if sr == SR:
        return x
    n = int(round(len(x) * SR / sr))
    t = np.arange(n) * (sr / SR)
    return np.stack([np.interp(t, np.arange(len(x)), x[:, c]) for c in range(x.shape[1])], axis=1)


def fft_filter(x, gain_of_hz):
    """Zero-phase filtering by a real magnitude response over the whole clip (a loop's content is
    circular anyway). Fast, which the sample-by-sample biquads it replaced were not."""
    X = np.fft.rfft(x, axis=0)
    X *= gain_of_hz(np.fft.rfftfreq(len(x), 1.0 / SR))[:, None]
    return np.fft.irfft(X, n=len(x), axis=0)


def highpass(x, hz):
    # 4th-order Butterworth magnitude.
    return fft_filter(x, lambda f: 1.0 / np.sqrt(1.0 + (hz / np.maximum(f, 1e-3)) ** 8)) if hz else x


def _biquad_mag(f, b, a):
    z = np.exp(-2j * np.pi * f / SR)
    return np.abs((b[0] + b[1] * z + b[2] * z * z) / (a[0] + a[1] * z + a[2] * z * z))


def lufs(x):
    """Ungated BS.1770 loudness (K-weighting at 48 kHz, applied as a magnitude response)."""
    b1, a1 = (1.53512485958697, -2.69169618940638, 1.19839281085285), (1.0, -1.69065929318241, 0.73248077421585)
    b2, a2 = (1.0, -2.0, 1.0), (1.0, -1.99004745483398, 0.99007225036621)
    y = fft_filter(x, lambda f: _biquad_mag(f, b1, a1) * _biquad_mag(f, b2, a2))
    ms = float(np.sum(np.mean(y ** 2, axis=0)))
    return -0.691 + 10 * math.log10(max(ms, 1e-20))


def resample_fft(x, n):
    """Exact for a loop: its content is periodic, so truncating the spectrum is an ideal low-pass."""
    X = np.fft.rfft(x, axis=0)
    keep = n // 2 + 1
    Y = np.zeros((keep, x.shape[1]), dtype=complex)
    m = min(keep, X.shape[0])
    Y[:m] = X[:m]
    return np.fft.irfft(Y, n=n, axis=0) * (n / len(x))


def make_loop(x, src):
    s0, s1, xf = int(src["start"] * SR), int(src["end"] * SR), int(src["xfade"] * SR)
    s1 = min(s1, len(x) - xf)
    if s1 - s0 < 4 * xf:
        sys.exit(f"{src['name']}: recording too short for [{src['start']}, {src['end']}) + {src['xfade']} s")
    seg = x[s0:s1 + xf].copy()
    L = s1 - s0
    t = np.linspace(0.0, 1.0, xf)[:, None]
    fade_in, fade_out = np.sin(t * math.pi / 2), np.cos(t * math.pi / 2)
    out = seg[:L].copy()
    out[:xf] = seg[L:L + xf] * fade_out + seg[:xf] * fade_in
    g = 10 ** ((src["lufs"] - lufs(out)) / 20)
    out *= g
    out = resample_fft(out, int(round(len(out) * LOOP_SR / SR)))
    peak = float(np.max(np.abs(out)))
    if peak > 0.97:
        out *= 0.97 / peak  # the loudness target would clip: keep the peak, report the shortfall
    return [out]


def make_events(x, src):
    mono = np.abs(x).max(axis=1)
    win = int(0.02 * SR)
    env = np.sqrt(np.convolve(mono ** 2, np.ones(win) / win, mode="same"))
    thr = env.max() * 10 ** (-src["thresh"] / 20)
    on = env > thr
    edges = np.flatnonzero(np.diff(on.astype(int)))
    if on[0]:
        edges = np.r_[0, edges]
    if on[-1]:
        edges = np.r_[edges, len(on) - 1]
    segs = [(a, b) for a, b in zip(edges[::2], edges[1::2]) if (b - a) >= src["min_s"] * SR]
    pad = int(0.08 * SR)
    segs = sorted(segs, key=lambda ab: -float(env[ab[0]:ab[1]].max()))[: src["count"]]
    out = []
    for a, b in sorted(segs):
        a, b = max(0, a - pad), min(len(x), b + pad * 3)
        e = x[a:b].copy()
        f = min(int(0.01 * SR), len(e) // 4)
        e[:f] *= np.linspace(0, 1, f)[:, None]
        e[-4 * f:] *= np.linspace(1, 0, 4 * f)[:, None]
        e *= 10 ** (src["peak"] / 20) / max(float(np.max(np.abs(e))), 1e-9)
        out.append(e)
    if not out:
        sys.exit(f"{src['name']}: no events found - lower 'thresh' or 'min_s'")
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("names", nargs="*")
    ap.add_argument("--audition", action="store_true")
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    report, credits, auditions = [], [], []
    for src in SOURCES:
        x, sr, meta = source_audio(src)
        credits.append(f"{src['name']}: \"{meta['title']}\" by {meta['author']} - https://freesound.org{src['page']} (CC0 1.0)")
        if a.names and src["name"] not in a.names:
            continue
        x = highpass(resample(x, sr), src.get("highpass", 0))
        parts = make_loop(x, src) if src["kind"] == "loop" else make_events(x, src)
        files = []
        for i, p in enumerate(parts):
            fname = f"{src['name']}.flac" if src["kind"] == "loop" else f"{src['name']}_{i + 1}.flac"
            rate = LOOP_SR if src["kind"] == "loop" else SR
            sf.write(os.path.join(OUT, fname), p.astype(np.float32), rate, subtype="PCM_16")
            files.append(fname)
            if a.audition:
                wav = os.path.join(CACHE, "audition_" + fname.replace(".flac", ".wav"))
                sf.write(wav, p.astype(np.float32), rate, subtype="PCM_16")
                auditions.append(wav)
        rate = LOOP_SR if src["kind"] == "loop" else SR
        report.append({"name": src["name"], "files": files, "seconds": [round(len(p) / rate, 1) for p in parts], "peak_dbfs": [round(20 * math.log10(max(float(np.max(np.abs(p))), 1e-9)), 1) for p in parts]})
    with open(os.path.join(OUT, "CREDITS.txt"), "w", encoding="utf-8") as f:
        f.write("Ambience recordings (generated by tools/make_ambience.py). All are CC0 1.0 (public domain\n"
                "dedication) from freesound.org; credit is given anyway, with thanks.\n\n")
        f.write("\n".join(credits) + "\n")
        f.write("\n" + ORIGINAL_NOTE)
    print(json.dumps(report, indent=1))
    if auditions:
        print("\nspectrograms: tools/harness/.venv/Scripts/python tools/harness/imgtools.py audio " +
              " ".join(os.path.relpath(w, REPO).replace("\\", "/") for w in auditions) + " -o build/ambience_cache/audition.png")


if __name__ == "__main__":
    main()
